### ISSUE TITLE
ImportError: cannot import name Q

### ISSUE THREAD

**Issue by alejandrojapkin** [swistakm/solrq#5]
ImportError: cannot import name Q

Library not working at all.

**Comment by swistakm** [comment]
It works in my environment:

```
swistakm@scotty:~$  virtualenv testenv-1
New python executable in testenv-1/bin/python
Installing setuptools, pip...done.

swistakm@scotty:~$ source testenv-1/bin/activate

(testenv-1)swistakm@scotty:~$ pip install solrq
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting solrq
  Downloading solrq-1.1.1-py2.py3-none-any.whl
Installing collected packages: solrq
Successfully installed solrq-1.1.1

(testenv-1)swistakm@scotty:~$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from solrq import Q
>>> Q(a=212) | Q(foo="bar")
<Q: a:212 OR foo:bar>
>>> ^D

(testenv-1)swistakm@scotty:~$ pip freeze
solrq==1.1.1
```

Could you share some more information on your environment?:
* Do you use virtualenv?
* Did you install solrq with pip?
* What distribution/version of Python do you use?
* Can you share full backtrace or at least the snippet of code that is responsible for this import?

You can also try to reproduce the steps from my example above.

**Comment by alvacouch** [comment]
@datascienceteam01 If you are using `solrq` in Django, the name `Q` is used for Django queries and you need to rename `Q` to some other name. 
```from solrq import Q as QR```
 This keeps it from colliding with Django `Q`.

**Comment by swistakm** [comment]
I close this as @datascienceteam01 did not provide more details.
